# Generated by Django 3.0.7 on 2020-06-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='Healthy',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
