# Generated by Django 3.0.7 on 2020-06-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_plant_healthy'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='PrevMeasure',
            field=models.CharField(default='NIL', max_length=512),
        ),
        migrations.AddField(
            model_name='plant',
            name='Symptom',
            field=models.CharField(default='NIL', max_length=256),
        ),
        migrations.DeleteModel(
            name='Symptoms',
        ),
    ]
